### ISSUE TITLE
Show line number for each offense

### ISSUE THREAD

**Issue by hanneskaeufler** [hanneskaeufler/danger-todoist#3]
In the table printed to the bottom of the danger comment, we can add the line number as well

**Comment by hanneskaeufler** [comment]
https://github.com/danger/danger/blob/master/CHANGELOG.md#330

There is not `info_for_file` which can be used to get the blob for a file after the changes made.

**Comment by hanneskaeufler** [comment]
Cool, thanks for posting, happy to see that. :) The feature would be cool, I am working on it in #40. Let's see how it goes, getting real line numbers from diffs is quite funky actually :D

**Comment by alex-mohemian** [comment]
I noticed that as well for another feature (I wanted to diff a `Gemfile` to see what exactly was added)

**Comment by hanneskaeufler** [comment]
You are welcome to try out the master branch, I have merged the work to show line numbers. I will release this as a 1.3.0 some time in the near(-ish) future.

**Comment by alex-mohemian** [comment]
@hanneskaeufler I did! Works great 👍 Thanks for adding this, it improves our PRs even further. Looking forward to the 1.3.0 release!

I did notice that the `text` property spans multiple lines if the following line is also a comment.

I.e.:

```
# TODO: change this
# gem 'xyz'
```

In this case, the `text` property will be `change this gem 'xyz'`. Different issue but just thought I let you know.

**Comment by alex-mohemian** [comment]
@hanneskaeufler do you have a planned date for the 1.3.0 release? 😉 🙏

**Comment by hanneskaeufler** [comment]
@alex-mohemian there it is, v1.3.0 hot off the press :)
